import { StyleSheet } from 'react-native';
import { COLORS } from '../../utils/colors';

export const useStyle = () => {
  return StyleSheet.create({
    startContainer: {
      flex: 1,
      justifyContent: 'center',
      width: '88%',
      alignSelf: 'center',
      paddingBottom: 120,
    },
    adView: {
      gap: 6,
      flexDirection: 'row',
      width: '32%',
      height: 40,
      alignSelf: 'flex-end',
      justifyContent: 'center',
      backgroundColor: COLORS.dark[500],
      borderRadius: 20,
      marginTop: 10,
      marginRight: 10,
      outlineColor: COLORS.blue[100],
      outlineWidth: 1,
    },
    welcomeTitle: {
      marginBottom: 16,
      textAlign: 'center',
    },
    welcomeSubtitle: {
      marginBottom: 40,
      textAlign: 'center',
      opacity: 0.8,
    },
    infoCard: {
      backgroundColor: COLORS.dark[800],
      padding: 24,
      borderRadius: 16,
      marginBottom: 40,
      width: '100%',
      borderWidth: 1,
      borderColor: COLORS.green[400],
      gap: 12,
    },
    infoText: {
      lineHeight: 24,
    },
    startButton: {
      backgroundColor: COLORS.green[400],
      paddingVertical: 20,
      paddingHorizontal: 60,
      borderRadius: 16,
      shadowColor: COLORS.green[400],
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.4,
      shadowRadius: 12,
      elevation: 8,
    },
    contentContainer: {
      width: '88%',
      alignSelf: 'center',
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 24,
    },
    categoryBadge: {
      backgroundColor: COLORS.dark[800],
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: COLORS.green[400],
    },
    questionCard: {
      backgroundColor: COLORS.dark[800],
      padding: 24,
      borderRadius: 16,
      marginBottom: 24,
      borderLeftWidth: 4,
      borderLeftColor: COLORS.green[400],
      shadowColor: COLORS.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    questionText: {
      lineHeight: 28,
    },
    optionsContainer: {
      gap: 12,
      marginBottom: 24,
    },
    option: {
      backgroundColor: COLORS.dark[800],
      padding: 16,
      borderRadius: 12,
      borderWidth: 2,
      borderColor: COLORS.dark[700],
    },
    correctOption: {
      backgroundColor: COLORS.trueOptionBGColor,
      borderColor: COLORS.trueOptionBorderColor,
      borderWidth: 2,
    },
    wrongOption: {
      backgroundColor: COLORS.falseOptionBGColor,
      borderColor: COLORS.falseOptionBorderColor,
      borderWidth: 2,
    },
    optionContent: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    optionNumber: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: COLORS.green[400],
      justifyContent: 'center',
      alignItems: 'center',
    },
    optionText: {
      flex: 1,
      lineHeight: 22,
    },
    nextButton: {
      backgroundColor: COLORS.green[400],
      padding: 18,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 8,
      marginBottom: 20,
      shadowColor: COLORS.green[400],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    resultContainer: {
      flex: 1,
      justifyContent: 'center',
      width: '85%',
      alignSelf: 'center',
      paddingBottom: 120,
    },
    resultTitle: {
      marginBottom: 40,
      textAlign: 'center',
    },
    scoreCard: {
      backgroundColor: COLORS.dark[800],
      padding: 40,
      borderRadius: 24,
      alignItems: 'center',
      marginBottom: 40,
      borderWidth: 2,
      borderColor: COLORS.green[400],
      shadowColor: COLORS.green[400],
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.3,
      shadowRadius: 16,
      elevation: 10,
    },
    scoreLabel: {
      marginBottom: 16,
      textTransform: 'uppercase',
      letterSpacing: 2,
    },
    scoreValue: {
      marginBottom: 8,
    },
    percentage: {
      opacity: 0.8,
    },
    resetButton: {
      backgroundColor: COLORS.green[400],
      paddingVertical: 18,
      paddingHorizontal: 40,
      borderRadius: 12,
      shadowColor: COLORS.green[400],
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 6,
    },
    bannerContainer: {
      position: 'absolute',
      bottom: 0,
      left: 0,
      right: 0,
      alignItems: 'center',
      backgroundColor: COLORS.background,
    },
  });
};
